apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  resources:
    - ../../apps/keycloak
    - ../../apps/minio
    - ../../apps/rabbitmq
    - ../../apps/sonar