apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq
      version: "8.29.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: docker.io/library/rabbitmq
      tag: 3-management
    persistence:
      enabled: true
      storageClass: "gp2"
      size: 8Gi
    service:
      type: ClusterIP
    extraPlugins: "rabbitmq_management"