apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarqube
      version: "10.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      enabled: true
    service:
      type: ClusterIP